### ISSUE TITLE
Feedback on projections

### ISSUE THREAD

**Issue by endger0125** [tbjw/ILAUBC#25]
In reference to version 854a7ec5708270d6a1abe1584fadcdc56d241314
<img width="702" alt="Screen Shot 2021-12-03 at 17 03 08" src="https://user-images.githubusercontent.com/93898036/144690658-51614832-807a-4069-8242-172449fdd282.png">
I'm confused. Shouldn't it be the null space of transpose of matrix B?
Please let me know if I'm wrong.

**Comment by tbjw** [comment]
Interesting question.

In the context of this list of properties, B is indeed meant. Since Bx is the projection of x onto W, we get Bx=0 if and only if x is in W^\perp.

Nonetheless, you are quite correct in remembering that if Col(B) = W, then Nul(B^T) = W^\perp. That's a general fact that's true for all matrices, not just projection matrices.

Putting together the two facts above, we see that Nul(B) = Nul(B^T) if B is the matrix of an orthogonal projection. That's interesting, but we can do even better:


Theorem: if B is the matrix of an orthogonal projection, then B=B^T.

Proof: We can write B = A(A^TA)^{-1} A^T for some matrix A. Then B^T = (A(A^TA)^(-1) A^T)^T. Remember that T reverses the order of multiplication, so B^T = A^(TT) * (A^TA)^(-1)^T A^T = A * (A^TA)^(-1)^T * A^T.

So far so good. It is even the case that (X^T)^(-1) = X^(-1)^T if X is invertible. With this in hand, our expression becomes

A((A^TA)^T)^(-1)A^T = A(A^TA)^(-1) A^T = B.

So in the end, B^T =B, and both what is in the book and what you expected are correct.
