### ISSUE TITLE
Feedback on orthogonal-complements

### ISSUE THREAD

**Issue by Candyzorua** [tbjw/ILAUBC#53]
In reference to version d2fe009538a800309f07adf0f13e646c9e9186f2

**
<img width="827" alt="image" src="https://github.com/tbjw/ILAUBC/assets/75513525/ef283d0c-fb2a-49a6-b936-0ea1e46b38d5">
**

Should this be Nul(A^T) instead of Nul(A)?

**Comment by Candyzorua** [comment]
From "Computing Orthogonal Complements", Part 7.2 Orthogonal Complements.

**Comment by tbjw** [comment]
Thanks for this question. Something is wrong here, because the proof is
referring to a "first equality" and a "second equality" but there is only
one equality in the statement. The same weirdness happens in the GA Tech
version of the textbook:
https://textbooks.math.gatech.edu/ila/orthogonal-complements.html

For now, you can be certain that the statement is correct, and also the
ideas in the 'proof' actually can be fixed to give a correct proof. In a
few days, when I have time, I will fix this proof up and write another
message.

Thanks again for asking this!

**Comment by tbjw** [comment]
This will be fixed in the next upload. The proof has been rewritten and another proposition has been added to clarify this one.
